var team = {
  'India': [
    {"pname": "Shikhar Dhawan", "img": "https://sportstar.thehindu.com/cricket/article27199614.ece/ALTERNATES/FREE_180/Shikhar-Dhawan", "country": "India"},
    {"pname": "Rohit Sharma", "img": "https://sportstar.thehindu.com/cricket/article27272628.ece/ALTERNATES/FREE_180/GettyImages-1151429390jpg", "country": "India"},
    {"pname": "Lokesh Rahul", "img": "https://sportstar.thehindu.com/cricket/article27199594.ece/ALTERNATES/FREE_180/KL-Rahul", "country": "India"},
    {"pname": "Virat Kohli", "img": "https://sportstar.thehindu.com/cricket/article27199618.ece/ALTERNATES/FREE_180/Virat-Kohli", "country": "India"},
    {"pname": "Mahendra Singh Dhoni", "img": "https://sportstar.thehindu.com/cricket/article27199604.ece/ALTERNATES/FREE_180/MS-Dhoni", "country": "India"},
    {"pname": "Kedar Jadhav", "img": "https://sportstar.thehindu.com/cricket/article27199588.ece/ALTERNATES/FREE_180/Kedar-Jadhav", "country": "India"},
    {"pname": "Vijay Shankar", "img": "https://sportstar.thehindu.com/cricket/article27199579.ece/ALTERNATES/FREE_180/Vijay-Shankar", "country": "India"},
    {"pname": "Dinesh Karthik", "img": "https://sportstar.thehindu.com/cricket/article27199552.ece/ALTERNATES/FREE_180/Dinesh-Karthik", "country": "India"},
    {"pname": "Hardik Pandya", "img": "https://sportstar.thehindu.com/cricket/article27199557.ece/ALTERNATES/FREE_180/Hardik-Pandya", "country": "India"},
    {"pname": "Ravindra Jadeja", "img": "https://sportstar.thehindu.com/cricket/article27199612.ece/ALTERNATES/FREE_180/Ravindra-Jadeja", "country": "India"},
    {"pname": "Bhuvneshwar Kumar", "img": "https://sportstar.thehindu.com/cricket/article27199534.ece/ALTERNATES/FREE_180/Bhuvneshwar-Kumar", "country": "India"},
    {"pname": "Mohammed Shami", "img": "https://sportstar.thehindu.com/cricket/article27199601.ece/ALTERNATES/FREE_180/Mohammed-Shami", "country": "India"},
    {"pname": "Jasprit Bumrah", "img": "https://sportstar.thehindu.com/cricket/article27199630.ece/ALTERNATES/FREE_180/Jasprit-Bumrah", "country": "India"},
    {"pname": "Kuldeep Yadav", "img": "https://sportstar.thehindu.com/cricket/article27199598.ece/ALTERNATES/FREE_180/Kuldeep-Yadav", "country": "India"},
    {"pname": "Yuzvendra Chahal", "img": "https://sportstar.thehindu.com/cricket/article27199619.ece/ALTERNATES/FREE_180/Yuzvendra-Chahal", "country": "India"}
    ],
  'England': [
    {"pname": "Eoin Morgan", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170936/eoin-morgan.jpg", "country": "England"},
    {"pname": "Joe Root", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170942/joe-root.jpg", "country": "England"},
    {"pname": "Jason Roy", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170941/jason-roy.jpg", "country": "England"},
    {"pname": "James Vince", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170945/james-vince.jpg", "country": "England"},
    {"pname": "Moeen Ali", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170953/moeen-ali.jpg", "country": "England"},
    {"pname": "Ben Stokes", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170950/ben-stokes.jpg", "country": "England"},
    {"pname": "Chris Woakes", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170964/chris-woakes.jpg", "country": "England"},
    {"pname": "Tom Curran", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170967/tom-curran.jpg", "country": "England"},
    {"pname": "Liam Dawson", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170968/liam-dawson.jpg", "country": "England"},
    {"pname": "Jofra Archer", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170970/jofra-archer.jpg", "country": "England"},
    {"pname": "Jonny Bairstow", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170976/jonny-bairstow.jpg", "country": "England"},
    {"pname": "Jos Buttler", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170980/jos-buttler.jpg", "country": "England"},
    {"pname": "Liam Plunkett", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170983/liam-plunkett.jpg", "country": "England"},
    {"pname": "Adil Rashid", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170987/adil-rashid.jpg", "country": "England"},
    {"pname": "Mark Wood", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170990/mark-wood.jpg", "country": "England"},

  ],
  'Australia': [
    {"pname": "Aaron Finch", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170630/aaron-finch.jpg", "country": "Australia"},
    {"pname": "Shaun Marsh", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170626/shaun-marsh.jpg", "country": "Australia"},
    {"pname": "Steven Smith", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170624/steven-smith.jpg", "country": "Australia"},
    {"pname": "David Warner", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170635/david-warner.jpg", "country": "Australia"},
    {"pname": "Usman Khawaja", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170640/usman-khawaja.jpg", "country": "Australia"},
    {"pname": "Glenn Maxwell", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170641/glenn-maxwell.jpg", "country": "Australia"},
    {"pname": "Marcus Stoinis", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c176605/marcus-stoinis.jpg", "country": "Australia"},
    {"pname": "Alex Carey", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170667/alex-carey.jpg", "country": "Australia"},
    {"pname": "Pat Cummins", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170651/pat-cummins.jpg", "country": "Australia"},
    {"pname": "Nathan Lyon", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170650/nathan-lyon.jpg", "country": "Australia"},
    {"pname": "Mitchell Starc", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170643/mitchell-starc.jpg", "country": "Australia"},
    {"pname": "Kane Richardson", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170638/kane-richardson.jpg", "country": "Australia"},
    {"pname": "Nathan Coulter-Nile", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170648/nathan-coulter-nile.jpg", "country": "Australia"},
    {"pname": "Jason Behrendorff", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170647/jason-behrendorff.jpg", "country": "Australia"},
    {"pname": "Adam Zampa", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170654/adam-zampa.jpg", "country": "Australia"}
  ],
  'Sri Lanka': [
    {"pname": "Lahiru Thirimanne", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170704/lahiru-thirimanne.jpg", "country": "Sri Lanka"},
    {"pname": "Dimuth Karunaratne", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170700/dimuth-karunaratne.jpg", "country": "Sri Lanka"},
    {"pname": "Avishka Fernando", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170702/avishka-fernando.jpg", "country": "Sri Lanka"},
    {"pname": "Angelo Mathews", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170706/angelo-mathews.jpg", "country": "Sri Lanka"},
    {"pname": "Dhananjaya de Silva", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170708/dhananjaya-de-silva.jpg", "country": "Sri Lanka"},
    {"pname": "Isuru Udana", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170710/isuru-udana.jpg", "country": "Sri Lanka"},
    {"pname": "Milinda Siriwardana", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170712/milinda-siriwardana.jpg", "country": "Sri Lanka"},
    {"pname": "Thisara Perera", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170714/thisara-perera.jpg", "country": "Sri Lanka"},
    {"pname": "Jeevan Mendis", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170716/jeevan-mendis.jpg", "country": "Sri Lanka"},
    {"pname": "Kusal Perera", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170718/kusal-perera.jpg", "country": "Sri Lanka"},
    {"pname": "Kusal Mendis", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170815/kusal-mendis.jpg", "country": "Sri Lanka"},
    {"pname": "Suranga Lakmal", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170726/suranga-lakmal.jpg", "country": "Sri Lanka"},
    {"pname": "Lasith Malinga", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170724/lasith-malinga.jpg", "country": "Sri Lanka"},
    {"pname": "Jeffrey Vandersay", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170722/jeffrey-vandersay.jpg", "country": "Sri Lanka"},
    {"pname": "Nuwan Pradeep", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170728/nuwan-pradeep.jpg", "country": "Sri Lanka"},
  ],
  'West Indies': [
    {"pname": "Darren Bravo", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170790/darren-bravo.jpg", "country": "West Indies"},
    {"pname": "Chris Gayle", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170801/chris-gayle.jpg", "country": "West Indies"},
    {"pname": "Evin Lewis", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170785/evin-lewis.jpg", "country": "West Indies"},
    {"pname": "Shimron Hetmyer", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c171232/shimron-hetmyer.jpg", "country": "West Indies"},
    {"pname": "Fabian Allen", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170794/fabian-allen.jpg", "country": "West Indies"},
    {"pname": "Jason Holder", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170806/jason-holder.jpg", "country": "West Indies"},
    {"pname": "Andre Russell", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170821/andre-russell.jpg", "country": "West Indies"},
    {"pname": "Carlos Brathwaite", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170798/carlos-brathwaite.jpg", "country": "West Indies"},
    {"pname": "Shai Hope", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170814/shai-hope.jpg", "country": "West Indies"},
    {"pname": "Nicholas Pooran", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170810/nicholas-pooran.jpg", "country": "West Indies"},
    {"pname": "Sheldon Cottrell", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170828/sheldon-cottrell.jpg", "country": "West Indies"},
    {"pname": "Shannon Gabriel", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170826/shannon-gabriel.jpg", "country": "West Indies"},
    {"pname": "Kemar Roach", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170820/kemar-roach.jpg", "country": "West Indies"},
    {"pname": "Ashley Nurse", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170817/ashley-nurse.jpg", "country": "West Indies"},
    {"pname": "Oshane Thomas", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170824/oshane-thomas.jpg", "country": "West Indies"},
  ],
  'South Africa': [
    {"pname": "Hashim Amla", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170633/hashim-amla.jpg", "country": "South Africa"},
    {"pname": "Faf du Plessis", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170639/faf-du-plessis.jpg", "country": "South Africa"},
    {"pname": "David Miller", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170687/david-miller.jpg", "country": "South Africa"},
    {"pname": "Aiden Markram", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170645/aiden-markram.jpg", "country": "South Africa"},
    {"pname": "Rassie van der Dussen", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170691/rassie-van-der-dussen.jpg", "country": "South Africa"},
    {"pname": "Jean-Paul Duminy", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170693/jean-paul-duminy.jpg", "country": "South Africa"},
    {"pname": "Andile Phehlukwayo", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170694/andile-phehlukwayo.jpg", "country": "South Africa"},
    {"pname": "Dwaine Pretorius", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170695/dwaine-pretorius.jpg", "country": "South Africa"},
    {"pname": "Chris Morris", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170696/chris-morris.jpg", "country": "South Africa"},
    {"pname": "Quinton de Kock", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170698/quinton-de-kock.jpg", "country": "South Africa"},
    {"pname": "Imran Tahir", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170764/imran-tahir.jpg", "country": "South Africa"},
    {"pname": "Kagiso Rabada", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170759/kagiso-rabada.jpg", "country": "South Africa"},
    {"pname": "Lungi Ngidi", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170761/lungi-ngidi.jpg", "country": "South Africa"},
    {"pname": "Tabraiz Shamsi", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170774/tabraiz-shamsi.jpg", "country": "South Africa"},
    {"pname": "Beuran Hendricks", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c157349/beuran-hendricks.jpg", "country": "South Africa"},
  ],
  'Afghanistan': [
    {"pname": "Asghar Afghan", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170835/asghar-afghan.jpg", "country": "Afghanistan"},
    {"pname": "Hashmatullah Shahidi", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170837/hashmatullah-shahidi.jpg", "country": "Afghanistan"},
    {"pname": "Hazratullah Zazai", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170833/hazratullah-zazai.jpg", "country": "Afghanistan"},
    {"pname": "Najibullah Zadran", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170839/najibullah-zadran.jpg", "country": "Afghanistan"},
    {"pname": "Noor Ali Zadran", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170831/noor-ali-zadran.jpg", "country": "Afghanistan"},
    {"pname": "Rahmat Shah", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170846/rahmat-shah.jpg", "country": "Afghanistan"},
    {"pname": "Samiullah Shinwari", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170849/samiullah-shinwari.jpg", "country": "Afghanistan"},
    {"pname": "Gulbadin Naib", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170851/gulbadin-naib.jpg", "country": "Afghanistan"},
    {"pname": "Mohammad Nabi", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170853/mohammad-nabi.jpg", "country": "Afghanistan"},
    {"pname": "Mohammad Shahzad", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170855/mohammad-shahzad.jpg", "country": "Afghanistan"},
    {"pname": "Aftab Alam", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170861/aftab-alam.jpg", "country": "Afghanistan"},
    {"pname": "Dawlat Zadran", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170859/dawlat-zadran.jpg", "country": "Afghanistan"},
    {"pname": "Hamid Hassan", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170863/hamid-hassan.jpg", "country": "Afghanistan"},
    {"pname": "Rashid Khan", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170857/rashid-khan.jpg", "country": "Afghanistan"},
    {"pname": "Mujeeb Ur Rahman", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170865/mujeeb-ur-rahman.jpg", "country": "Afghanistan"},
  ],
  'New Zealand': [
    {"pname": "Martin Guptill", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170731/martin-guptill.jpg", "country": "New Zealand"},
    {"pname": "Ross Taylor", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170729/ross-taylor.jpg", "country": "New Zealand"},
    {"pname": "Kane Williamson", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170733/kane-williamson.jpg", "country": "New Zealand"},
    {"pname": "James Neesham", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170739/james-neesham.jpg", "country": "New Zealand"},
    {"pname": "Colin de Grandhomme", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170735/colin-de-grandhomme.jpg", "country": "New Zealand"},
    {"pname": "Colin Munro", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170737/colin-munro.jpg", "country": "New Zealand"},
    {"pname": "Mitchell Santner", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170741/mitchell-santner.jpg", "country": "New Zealand"},
    {"pname": "Tom Latham", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170743/tom-latham.jpg", "country": "New Zealand"},
    {"pname": "Henry Nicholls", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170745/henry-nicholls.jpg", "country": "New Zealand"},
    {"pname": "Tom Blundell", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170757/tom-blundell.jpg", "country": "New Zealand"},
    {"pname": "Trent Boult", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170747/trent-boult.jpg", "country": "New Zealand"},
    {"pname": "Matt Henry", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170751/matt-henry.jpg", "country": "New Zealand"},
    {"pname": "Tim Southee", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170753/tim-southee.jpg", "country": "New Zealand"},
    {"pname": "Ish Sodhi", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170755/ish-sodhi.jpg", "country": "New Zealand"},
    {"pname": "Lockie Ferguson", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170749/lockie-ferguson.jpg", "country": "New Zealand"},
  ],
  'Pakistan': [
    {"pname": "Fakhar Zaman", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170763/fakhar-zaman.jpg", "country": "Pakistan"},
    {"pname": "Imam-ul-Haq", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170765/imam-ul-haq.jpg", "country": "Pakistan"},
    {"pname": "Babar Azam", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170768/babar-azam.jpg", "country": "Pakistan"},
    {"pname": "Asif Ali", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170770/asif-ali.jpg", "country": "Pakistan"},
    {"pname": "Haris Sohail", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170777/haris-sohail.jpg", "country": "Pakistan"},
    {"pname": "Mohammad Hafeez", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170776/mohammad-hafeez.jpg", "country": "Pakistan"},
    {"pname": "Shoaib Malik", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170775/shoaib-malik.jpg", "country": "Pakistan"},
    {"pname": "Shadab Khan", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170779/shadab-khan.jpg", "country": "Pakistan"},
    {"pname": "Imad Wasim", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170782/imad-wasim.jpg", "country": "Pakistan"},
    {"pname": "Sarfaraz Ahmed", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170787/sarfaraz-ahmed.jpg", "country": "Pakistan"},
    {"pname": "Wahab Riaz", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170809/wahab-riaz.jpg", "country": "Pakistan"},
    {"pname": "Shaheen Afridi", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170802/shaheen-afridi.jpg", "country": "Pakistan"},
    {"pname": "Hasan Ali", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170804/hasan-ali.jpg", "country": "Pakistan"},
    {"pname": "Mohammad Hasnain", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170805/mohammad-hasnain.jpg", "country": "Pakistan"},
    {"pname": "Mohammad Amir", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170813/mohammad-amir.jpg", "country": "Pakistan"},
  ],
  'Bangladesh': [
    {"pname": "Tamim Iqbal", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170899/tamim-iqbal.jpg", "country": "Bangladesh"},
    {"pname": "Soumya Sarkar", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170900/soumya-sarkar.jpg", "country": "Bangladesh"},
    {"pname": "Sabbir Rahman", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170903/sabbir-rahman.jpg", "country": "Bangladesh"},
    {"pname": "Mahmudullah", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170905/mahmudullah.jpg", "country": "Bangladesh"},
    {"pname": "Shakib Al Hasan", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170912/shakib-al-hasan.jpg", "country": "Bangladesh"},
    {"pname": "Mohammad Saifuddin", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170907/mohammad-saifuddin.jpg", "country": "Bangladesh"},
    {"pname": "Mosaddek Hossain", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170909/mosaddek-hossain.jpg", "country": "Bangladesh"},
    {"pname": "Mehidy Hasan", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c148289/mehidy-hasan.jpg", "country": "Bangladesh"},
    {"pname": "Mushfiqur Rahim", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170916/mushfiqur-rahim.jpg", "country": "Bangladesh"},
    {"pname": "Liton Das", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170914/liton-das.jpg", "country": "Bangladesh"},
    {"pname": "Mohammad Mithun", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170918/mohammad-mithun.jpg", "country": "Bangladesh"},
    {"pname": "Mashrafe Mortaza", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170920/mashrafe-mortaza.jpg", "country": "Bangladesh"},
    {"pname": "Rubel Hossain", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170922/rubel-hossain.jpg", "country": "Bangladesh"},
    {"pname": "Mustafizur Rahman", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170925/mustafizur-rahman.jpg", "country": "Bangladesh"},
    {"pname": "Abu Jayed", "img": "https://www.cricbuzz.com/a/img/v1/75x75/i1/c170927/abu-jayed.jpg", "country": "Bangladesh"},
  ],
};

